name: "CI"

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Linting test
        run: yarn lint

      - name: Build test
        run: yarn build
